name: Pipeline test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Validate pipeline.yml syntax
      run: |
        # Run any command to test your pipeline syntax (for example, linter or dry run)
        echo "Testing pipeline syntax"