name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Less Dependencies
        run: |
            npm install less
            npm install less-plugin-clean-css
            npm install terser


      - name: Run Tests
        run: echo "Running tests..."
