name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm install less # Install 'lessc'

      - name: Run Tests
        run: echo "Running tests..."
