name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Less Dependencies
        run: npm install less

      - name: Install Clean CSS plugin
        run: npm install less-plugin-clean-css

      - name: Run Tests
        run: echo "Running tests..."
