name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Less Dependencies
        run: |
            npm install less less-plugin-clean-css terser

      - name: Clean CSS
        run: npx lessc -clean-css ./assets/css/site.less ./assets/css/site.css --clean-css

      - name: Run Tests
        run: echo "Running tests..."
